filter:
    paths: [src/*]
    excluded_paths: [vendor/*, tests/*]
before_commands:
    - 'composer install --dev --prefer-source'
checks:
    php:
        uppercase_constants: true
        verify_property_names: true
        verify_argument_usable_as_reference: true
        verify_access_scope_valid: true
        variable_existence: true
        unused_variables: true
        unused_properties: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        spacing_of_function_arguments: true
        spacing_around_conditional_operators: true
        single_namespace_per_use: true
        simplify_boolean_return: true
        side_effects_or_types: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_php_tag_first: true
        require_braces_around_control_structures: true
        precedence_mistakes: true
        precedence_in_conditions: true
        php5_style_constructor: true
        parameter_non_unique: true
        overriding_private_members: true
        non_commented_empty_catch_block: true
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        no_global_keyword: true
        no_eval: true
        no_error_suppression: true
        no_empty_statements: true
        no_debug_code: true
        missing_arguments: true
        lowercase_php_keywords: true
        lowercase_basic_constants: true
        ensure_lower_case_builtin_functions: true
        encourage_single_quotes: true
        deprecated_code_usage: true
        code_rating: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        classes_in_camel_caps: true
        catch_class_exists: true
        avoid_usage_of_logical_operators: true
        avoid_todo_comments: true
        avoid_superglobals: true
        avoid_multiple_statements_on_same_line: true
        avoid_duplicate_types: true
        avoid_closing_tag: true
