filter:
    paths: [src/*]
    excluded_paths: [vendor/*, tests/*]
before_commands:
    - 'composer install --dev --prefer-source'
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_mess_detector: true